version: '3'
services:
  mysqlsamuel:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_DATABASE: uaa
    networks:
      - uaa-net

  admineruaa:
    image: adminer
    restart: always
    ports:
      - 9091:8080
    networks:
      - uaa-net

networks:
  uaa-net:
    driver: bridge

